### ISSUE TITLE
Regal support for extended GL support (compat profile & more..)

### ISSUE THREAD

**Issue by oscarbg** [kbiElude/VKGL#1]
Hi,
Interesting project.. will follow it..
Do you know about https://github.com/p3/regal ?
Maybe useful as it extends GL core implementations with some compatibility functions and beyond..
Suposedly emulation is not super slow and I think is done calling only GL core functions..
Thanks..

**Comment by kbiElude** [comment]
Thanks for the feed-back!

Compatibility profile is a *long* way from where the project currently stands so I'd prefer to refrain from drafting such long-term plans. I'm aware of Regal but have never worked with their codebase so there's not much I can comment on for now.

Keeping the options open for sure and definitely looking forward to seeing contributions from the community! Let's wait until VKGL can actually run some real GL core applications; once that happens, let's reopen this topic.
