### ISSUE TITLE
What is the proper operation of VLGK about 0 is bound when copying client memory

### ISSUE THREAD

**Issue by Michael-Lfx** [kbiElude/VKGL#10]
Let's say what should VKGL do when something like ```glBindTexture(GL_TEXTURE_2D, 0); glTexImage(some pixels)``` happens. Should it be ignored or just copy pixels to the default gl object we created for protection?

**Comment by Michael-Lfx** [comment]
`/dev/null` means that you will not create default texture object for all the texture targets? What will you do when querying parameters from `0` like `glBindTexture(GL_TEXTURE_2D, 0); glGetTexParameteriv(...)`?

**Comment by kbiElude** [comment]
Texture manager in the frontend does already create a default texture object (ie. with ID 0) but any GL function that updates mips (incl. implicit texture state updates, as is in the case of glTexImage*() calls) triggers an assertion failure in vkgl_not_implemented(). Adding support for textures has a TODO status at the moment.

Rest assured, it's not going to be a problem to implement whatever behavior is required by the spec.
