### ISSUE TITLE
Is that any chance to write it in Rust?

### ISSUE THREAD

**Issue by Michael-Lfx** [kbiElude/VKGL#9]
This is an amazing project. Is that any chances to write it in Rust language? Another question: how many developers engaged in the project? It seems that only you keep committing codes.

**Comment by kbiElude** [comment]
Thank you for the kind words.

One thing that needs to be stressed is that VKGL is not the kind of a project I would personally use as a vehicle for learning new programming languages. Given the complexity of the logic in backend, as well as its multithreaded construction, any attempt to kill two birds with one stone would greatly increase the likelihood of the project just dying out at some point.

Another reason I would prefer to stay with C++ is great availability of third-party libraries I am intending to use. While not used jyet, thread pools are one area which I would prefer not to have to reinvent from scratch. Sure, there may be some already written in Rust, but my lack of expertise in that language could have a detrimental effect on the pace, at which the project is progressing.

VKGL is a hobby project I am doing in my free time (which is scarce these days, and which is also why I tend to commit most of the changes overnight). It has a huge potential for community contributions (validation being one of primary examples of where this support will be hugely appreciated) and I am hoping to leverage it at some point, assuming there are people interested in giving a hand. That being said, core infrastructure needs to be carefully designed & implemented in order for the whole machine not fall apart. That's what I've been working on for the last three months. It will take a fair number of months though before the project can be used for running anything more demanding except the LearnOpenGL examples which I use as a bring-up platform for the project.

As I mentioned, this is a hobby project. I have a fair amount of experience, working on conformance tests for OpenGL and OpenGL ES and Vulkan is what pays my mortgage these days, so VKGL seemed like an interesting opportunity to put this experience into something that some people might find useful one day. There are no other parties involved and - frankly - that suits me just fine **for now**. The problem we are trying to solve in VKGL is non-trivial; as far as I am aware, no other project that does OpenGL-on-Vulkan has similar approach as I do.. which is also what makes this an interesting project to spend free evening cycles on :-)
